=== AdrianT12345/University-coursework/hypertext-and-hypermedia/project_my_hobby_website/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">


    <xs:simpleType name="StatusTyp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="aktywny"/>
            <xs:enumeration value="kontuzjowany"/>
            <xs:enumeration value="nieaktywny"/>
            <xs:enumeration value="zawieszony"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="KodPocztowyTyp">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}-\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="WzrostTyp">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="100"/>
            <xs:maxInclusive value="250"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CenaTyp">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ListaWynikowTyp">
        <xs:list itemType="xs:decimal"/>
    </xs:simpleType>
    
    <xs:simpleType name="OstatnieCzasyTyp">
        <xs:restriction base="ListaWynikowTyp">
            <xs:minLength value="0"/>
            <xs:maxLength value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MiejsceLiczboweTyp">
        <xs:restriction base="xs:positiveInteger">
            <xs:maxInclusive value="1000"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="StatusRankinguTyp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Niesklasyfikowany"/>
            <xs:enumeration value="DSQ"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="RankingTyp">
        <xs:union memberTypes="MiejsceLiczboweTyp StatusRankinguTyp"/>
    </xs:simpleType>

    <xs:simpleType name="KrotkiTekstTyp">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
            <xs:minLength value="2"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:group name="GrupaAdresowa">
        <xs:sequence>
            <xs:element name="Ulica" type="xs:string"/>
            <xs:element name="KodPocztowy" type="KodPocztowyTyp"/>
            <xs:element name="Miasto" type="xs:string"/>
        </xs:sequence>
    </xs:group>

    <xs:attribute name="id" type="xs:ID"/>


    <xs:complexType name="AdresTyp">
        <xs:group ref="GrupaAdresowa"/>
    </xs:complexType>

    <xs:complexType name="AutorTyp">
        <xs:sequence>
            <xs:element name="Imie" type="KrotkiTekstTyp"/>
            <xs:element name="Nazwisko" type="KrotkiTekstTyp"/>
            <xs:element name="Indeks" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DaneOsoboweTyp">
        <xs:sequence>
            <xs:element name="Imie" type="KrotkiTekstTyp"/>
            <xs:element name="Nazwisko" type="KrotkiTekstTyp"/>
            <xs:element name="DataUrodzenia" type="xs:date" minOccurs="0"/>
            <xs:element name="Plec">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[KM]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BiografiaTyp" mixed="true">
        <xs:sequence>
            <xs:element name="Wyroznienie" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ParametrTyp">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="jednostka" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="ZdjecieTyp">
        <xs:complexContent>
            <xs:restriction base="xs:anyType">
                <xs:attribute name="url" type="xs:anyURI" use="required"/>
                <xs:attribute name="format" type="xs:string"/>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="ZdjecieZOpisemTyp">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="url" type="xs:anyURI" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:element name="ZdjecieProfilowe" type="ZdjecieTyp"/>

    <xs:element name="PortalLekkoatletyczny">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="Naglowek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Autor" type="AutorTyp"/>
                            <xs:element name="Temat" type="xs:string"/>
                            <xs:element name="Opis" type="xs:string"/>
                            <xs:element name="WersjaProjektu" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="ZwiazekSportowy">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="NazwaPelna" type="xs:string"/>
                            <xs:element name="Adres" type="AdresTyp"/>
                            <xs:element name="Kontakt" type="xs:string"/>
                            <xs:element name="StronaOficjalna" type="xs:anyURI"/>
                        </xs:sequence>
                        <xs:attribute name="kraj" type="xs:string" default="Polska"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Kluby">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Klub" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nazwa" type="xs:string"/>
                                        <xs:element name="DataZalozenia" type="xs:date"/>
                                        
                                        <xs:element name="Sekcja" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Kierownik" type="xs:string"/>
                                                    <xs:element name="Zawodnicy">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                
                                                                <xs:element name="Zawodnik" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="DaneOsobowe" type="DaneOsoboweTyp"/>
                                                                            <xs:element name="Biografia" type="BiografiaTyp"/>
                                                                            
                                                                            <xs:element name="ParametryFizyczne">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="Wzrost" type="ParametrTyp"/>
                                                                                        <xs:element name="Waga" type="ParametrTyp"/>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>

                                                                            <xs:element name="Osiagniecia">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="RankingKrajowy" type="RankingTyp"/>
                                                                                        
                                                                                        <xs:element name="OstatnieCzasy">
                                                                                            <xs:complexType>
                                                                                                <xs:simpleContent>
                                                                                                    <xs:extension base="OstatnieCzasyTyp">
                                                                                                        <xs:attribute name="format" type="xs:string"/>
                                                                                                    </xs:extension>
                                                                                                </xs:simpleContent>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                        
                                                                                        <xs:element name="Rekordy" minOccurs="0">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element name="RekordDystans" maxOccurs="unbounded">
                                                                                                        <xs:complexType>
                                                                                                            <xs:sequence>
                                                                                                                <xs:element name="Wynik" type="xs:decimal"/>
                                                                                                                <xs:element name="Data" type="xs:date"/>
                                                                                                                <xs:element name="Miejsce" type="xs:string"/>
                                                                                                            </xs:sequence>
                                                                                                            <xs:attribute name="dystans" type="xs:string"/>
                                                                                                            <xs:attribute name="hala" type="xs:string"/>
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>

                                                                            <xs:element name="Multimedia">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element ref="ZdjecieProfilowe"/>
                                                                                        <xs:element name="Galeria">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element name="Zdjecie" type="ZdjecieZOpisemTyp" maxOccurs="unbounded"/>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                        <xs:element name="SocialMedia" minOccurs="0">
                                                                                            <xs:complexType>
                                                                                                <xs:simpleContent>
                                                                                                    <xs:extension base="xs:anyURI">
                                                                                                        <xs:attribute name="platforma" type="xs:string"/>
                                                                                                    </xs:extension>
                                                                                                </xs:simpleContent>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>

                                                                        </xs:sequence>
                                                                        <xs:attribute ref="id" use="required"/>
                                                                        <xs:attribute name="status" type="StatusTyp" use="optional"/>
                                                                    </xs:complexType>
                                                                </xs:element> 

                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="nazwa" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                    <xs:attribute ref="id"/>
                                    <xs:attribute name="licencja" type="xs:string"/>
                                    <xs:attribute name="typ" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Bilety">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Bilet" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="typ" type="xs:string"/>
                                            <xs:attribute name="cena" type="CenaTyp"/>
                                            <xs:attribute name="waluta" type="xs:string" fixed="PLN"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
        
        <xs:key name="KluczZawodnikID">
            <xs:selector xpath=".//Kluby/Klub/Sekcja/Zawodnicy/Zawodnik"/>
            <xs:field xpath="@id"/>
        </xs:key>

    </xs:element>

</xs:schema>

=== AdrianT12345/University-coursework/hypertext-and-hypermedia/project_my_hobby_website/lekkoatletyka.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="widok.xsl"?>
<PortalLekkoatletyczny xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    
    <Naglowek>
        <Autor>
            <Imie>Adrian</Imie>
            <Nazwisko>Trojak</Nazwisko>
            <Indeks>208249</Indeks>
        </Autor>
        <Temat>Lekkoatletyka - Królowa Sportu</Temat>
        <Opis>Projekt bazy danych opisujący struktury klubowe.</Opis>
        <WersjaProjektu>Finalna v2</WersjaProjektu>
    </Naglowek>

    <ZwiazekSportowy kraj="Polska">
        <NazwaPelna>Polski Związek Lekkiej Atletyki</NazwaPelna>
        <Adres>
            <Ulica>Mickiewicza 12</Ulica>
            <KodPocztowy>01-100</KodPocztowy>
            <Miasto>Warszawa</Miasto>
        </Adres>
        <Kontakt>biuro@pzla.pl</Kontakt>
        <StronaOficjalna>https://www.pzla.pl</StronaOficjalna>
    </ZwiazekSportowy>

    <Kluby>
        <Klub id="K-01" licencja="KL-2024-WAR" typ="akademicki">
            <Nazwa>AZS AWF Warszawa</Nazwa>
            <DataZalozenia>1949-05-12</DataZalozenia>
            
            <Sekcja nazwa="Sprint">
                <Kierownik>Piotr Kowalski</Kierownik>
                <Zawodnicy>
                    <Zawodnik id="Z-101" status="aktywny">
                        <DaneOsobowe>
                            <Imie>Ewa</Imie>
                            <Nazwisko>Swoboda</Nazwisko>
                            <DataUrodzenia>1997-07-26</DataUrodzenia>
                            <Plec>K</Plec>
                        </DaneOsobowe>
                        
                        <Biografia>
                            Specjalistka od biegów na krótkich dystansach. 
                            Wielokrotna <Wyroznienie>mistrzyni kraju</Wyroznienie> oraz medalistka halowych mistrzostw Europy.
                        </Biografia>

                        <ParametryFizyczne>
                            <Wzrost jednostka="cm">164</Wzrost>
                            <Waga jednostka="kg">55.5</Waga>
                        </ParametryFizyczne>

                        <Osiagniecia>
                            <RankingKrajowy>1</RankingKrajowy>
                            <OstatnieCzasy format="s">11.05 10.99 11.02 11.15</OstatnieCzasy>
                            <Rekordy>
                                <RekordDystans dystans="60m" hala="tak">
                                    <Wynik>6.99</Wynik>
                                    <Data>2022-03-05</Data>
                                    <Miejsce>Torun</Miejsce>
                                </RekordDystans>
                            </Rekordy>
                        </Osiagniecia>
                        
                        <Multimedia>
                            <ZdjecieProfilowe format="jpg" url="ewa_swoboda.jpg"/>
                            <Galeria>
                                <Zdjecie url="https://placehold.co/600x400?text=Start">Start z bloków</Zdjecie>
                            </Galeria>
                            <SocialMedia platforma="Instagram">https://instagram.com/ewa_swoboda</SocialMedia>
                        </Multimedia>
                    </Zawodnik>
                </Zawodnicy>
            </Sekcja>
        </Klub>

        <Klub id="K-02" licencja="KL-2024-POD" typ="miejski">
            <Nazwa>Podlasie Białystok</Nazwa>
            <DataZalozenia>1970-01-01</DataZalozenia>
            <Sekcja nazwa="Rzuty">
                <Kierownik>Marek Rzepkowski</Kierownik>
                <Zawodnicy>
                    <Zawodnik id="Z-102" status="aktywny">
                        <DaneOsobowe>
                            <Imie>Wojciech</Imie>
                            <Nazwisko>Nowicki</Nazwisko>
                            <DataUrodzenia>1989-02-22</DataUrodzenia>
                            <Plec>M</Plec>
                        </DaneOsobowe>
                        <Biografia>
                            Polski lekkoatleta specjalizujący się w rzucie młotem. 
                            Mistrz olimpijski z Tokio 2020. <Wyroznienie>Złoty medalista</Wyroznienie> mistrzostw Europy.
                        </Biografia>
                        <ParametryFizyczne>
                            <Wzrost jednostka="cm">196</Wzrost>
                            <Waga jednostka="kg">120.0</Waga>
                        </ParametryFizyczne>
                        <Osiagniecia>
                            <RankingKrajowy>1</RankingKrajowy>
                            <OstatnieCzasy format="m">80.00 81.90 79.50</OstatnieCzasy>
                            <Rekordy>
                                <RekordDystans dystans="Młot" hala="nie">
                                    <Wynik>82.52</Wynik>
                                    <Data>2021-08-04</Data>
                                    <Miejsce>Tokio</Miejsce>
                                </RekordDystans>
                            </Rekordy>
                        </Osiagniecia>
                        <Multimedia>
                            <ZdjecieProfilowe format="jpg" url="wojciech_nowicki.jpg"/>
                            <Galeria>
                                <Zdjecie url="https://placehold.co/600x400?text=Rzut">Technika obrotowa</Zdjecie>
                            </Galeria>
                            <SocialMedia platforma="Facebook">https://facebook.com/wojciechnowicki</SocialMedia>
                        </Multimedia>
                    </Zawodnik>

                    <Zawodnik id="Z-999" status="nieaktywny">
                        <DaneOsobowe>
                            <Imie>Jan</Imie>
                            <Nazwisko>Testowy</Nazwisko>
                            <DataUrodzenia>2000-01-01</DataUrodzenia>
                            <Plec>M</Plec>
                        </DaneOsobowe>
                        <Biografia>Zawodnik testowy do celów administracyjnych.</Biografia>
                        <ParametryFizyczne>
                            <Wzrost jednostka="cm">180</Wzrost>
                            <Waga jednostka="kg">75.0</Waga>
                        </ParametryFizyczne>
                        <Osiagniecia>
                            <RankingKrajowy>Niesklasyfikowany</RankingKrajowy>
                            <OstatnieCzasy format="m">0.0</OstatnieCzasy> 
                        </Osiagniecia>
                        <Multimedia>
                            <ZdjecieProfilowe format="png" url="jan-testowy.png"/>
                            <Galeria>
                                <Zdjecie url="https://placehold.co/600x400?text=Pusto">Brak zdjęć</Zdjecie>
                            </Galeria>
                            <SocialMedia platforma="Brak">https://brak.pl</SocialMedia>
                        </Multimedia>
                    </Zawodnik>
                </Zawodnicy>
            </Sekcja>
        </Klub>
    </Kluby>

    <Bilety>
        <Bilet typ="ulgowy" cena="20.00" waluta="PLN">Wejściówka</Bilet>
        <Bilet typ="normalny" cena="40.00" waluta="PLN">Wejściówka</Bilet>
    </Bilety>

</PortalLekkoatletyczny>
